# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\coordinates\popupWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class PopupWindow(QtWidgets.QWidget):
    def __init__(self, form):
        super().__init__()

        form.setObjectName("Form")
        form.resize(1024, 601)
        form.setStyleSheet("QWidget {\n"
                           "background-color: #171923;\n"
                           "}")
        self.image = QtWidgets.QLabel(form)
        self.image.setGeometry(QtCore.QRect(0, 0, 1024, 576))
        self.image.setFrameShape(QtWidgets.QFrame.Box)
        self.image.setLineWidth(0)
        self.image.setText("")
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setObjectName("image")
        self.saveImage = QtWidgets.QPushButton(form)
        self.saveImage.setGeometry(QtCore.QRect(924, 576, 100, 25))
        self.saveImage.setStyleSheet("QPushButton {\n"
                                     "background-color: #FFE81F;\n"
                                     "border: none;\n"
                                     "font-size: 11px;\n"
                                     "color: black;\n"
                                     "font-weight: 600;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:hover {\n"
                                     "background-color: #ccba18;\n"
                                     "\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:pressed {\n"
                                     "background-color: #ccba18;\n"
                                     "}\n"
                                     "\n"
                                     "QPushButton:disabled {\n"
                                     "    background-color:  #87814c;\n"
                                     "}")
        self.saveImage.setObjectName("saveImage")
        self.color1 = QtWidgets.QPushButton(form)
        self.color1.setGeometry(QtCore.QRect(890, 576, 25, 25))
        self.color1.setStyleSheet("QPushButton {\n"
                                  "    border: 5px solid #FFE81F;\n"
                                  "}")
        self.color1.setText("")
        self.color1.setObjectName("color1")
        self.color2 = QtWidgets.QPushButton(form)
        self.color2.setGeometry(QtCore.QRect(856, 576, 25, 25))
        self.color2.setStyleSheet("QPushButton {\n"
                                  "    border: 5px solid #FFE81F;\n"
                                  "}")
        self.color2.setText("")
        self.color2.setObjectName("color2")
        self.thresholdInput = QtWidgets.QLineEdit(form)
        self.thresholdInput.setGeometry(QtCore.QRect(0, 576, 100, 25))
        self.thresholdInput.setStyleSheet("QLineEdit {\n"
                                          "border: 1px solid #FFE81F;\n"
                                          "color: white;\n"
                                          "}")
        self.thresholdInput.setObjectName("thresholdInput")
        self.thresholdButton = QtWidgets.QPushButton(form)
        self.thresholdButton.setGeometry(QtCore.QRect(100, 576, 100, 25))
        self.thresholdButton.setStyleSheet("QPushButton {\n"
                                           "background-color: #FFE81F;\n"
                                           "border: none;\n"
                                           "font-size: 11px;\n"
                                           "color: black;\n"
                                           "font-weight: 600;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:hover {\n"
                                           "background-color: #ccba18;\n"
                                           "\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:pressed {\n"
                                           "background-color: #ccba18;\n"
                                           "}\n"
                                           "\n"
                                           "QPushButton:disabled {\n"
                                           "    background-color:  #87814c;\n"
                                           "}")
        self.thresholdButton.setObjectName("thresholdButton")

        self.retranslate_ui(form)
        QtCore.QMetaObject.connectSlotsByName(form)

    def retranslate_ui(self, form):
        _translate = QtCore.QCoreApplication.translate
        form.setWindowTitle(_translate("Form", "Form"))
        self.saveImage.setText(_translate("Form", "Save Image"))
        self.thresholdButton.setText(_translate("Form", "Apply Threshold"))
